### ISSUE TITLE
rofi-pass

### ISSUE THREAD

**Issue by rEnr3n** [tijn/awesome-password-store#18]
Please add this link.

https://github.com/carnager/rofi-pass

**Comment by tijn** [comment]
@rEnr3n it will be quickest when you send a pull request 😉

**Comment by rEnr3n** [comment]
I was not sure what category to put it in. Anyway, I made a PR.

**Comment by tijn** [comment]
> I was not sure what category to put it in. Anyway, I made a PR.

Oh, when someone else thinks it's in the wrong category it will be moved around, no worries!

**Comment by tijn** [comment]
Solved by #19
