### ISSUE TITLE
Windows usage

### ISSUE THREAD

**Issue by eutampieri** [tijn/awesome-password-store#22]
Hi, I had a hard time setting up pass on windows so I’ve written a [guide](https://blog.eutampieri.eu/pass-win/), hope that it will help someone

**Comment by tijn** [comment]
I'm closing this because ... it's not an issue, right?

Maybe we could create a new document, or another chapter to the exiting one with links to guides like these? I wonder if it would really be useful though. Anyway: please create pull requests :smile:

**Comment by eutampieri** [comment]
Yes, why didn’t I create a pull request? Anyway, most pass users don’t use windows so…

**Comment by erayd** [comment]
> Anyway, most pass users don’t use windows so…

Some certainly do though, IMO enough to make such a guide useful. We see support requests for windows users of pass (often via WSL, but some are native) fairly regularly in the [Browserpass](/browserpass/browserpass-extension) issue trackers.
