### ISSUE TITLE
Copy missing clients/interfaces from passwordstore.org

### ISSUE THREAD

**Issue by tijn** [tijn/awesome-password-store#9]
I already copied all extensions but I have to double check the list of clients from passwordstore.org to see if we have everything:

https://www.passwordstore.org/#other

**Comment by tijn** [comment]
solved by #14 😄

**Comment by tijn** [comment]
We're not sure we got the whole list yet 😬

**Comment by adur1990** [comment]
Here is a comprehensive list:

- [ ] [passmenu](https://git.zx2c4.com/password-store/tree/contrib/dmenu)
- [ ] [qtpass](https://qtpass.org)
- [X] [Android-Password-Store](https://github.com/android-password-store/Android-Password-Store)
- [X] [passforios](https://mssun.github.io/passforios/)
- [ ] [pass-ios](https://github.com/davidjb/pass-ios)
- [X] [passff](https://github.com/passff/passff)
- [ ] [Browserpass-legacy](https://github.com/browserpass/browserpass-legacy)
- [ ] [Pass4win](https://github.com/mbos/Pass4Win)
- [ ] [pext_module_pass](https://github.com/Pext/pext_module_pass)
- [ ] [Gopass](https://github.com/cortex/gopass)
- [ ] [upass](https://github.com/Kwpolska/upass)
- [X] [alfred-pass](https://github.com/CGenie/alfred-pass)
- [X] [pass-alfred](https://github.com/MatthewWest/pass-alfred)
- [X] simple-pass-alfred: Not availabel anymore!
- [X] [pass.applescript](https://git.zx2c4.com/password-store/tree/contrib/pass.applescript)
- [ ] [pass-git-helper](https://github.com/languitar/pass-git-helper)
- [ ] [password-store.el](https://git.zx2c4.com/password-store/tree/contrib/emacs)
- [ ] [XMonad.Prompt.Pass](https://hackage.haskell.org/package/xmonad-contrib-0.13/docs/XMonad-Prompt-Pass.html)

**Comment by erayd** [comment]
@adur1990 The BrowserPass link in that list is wrong - it should be https://github.com/browserpass/browserpass-extension

We've tried to have the link on that site corrected, but our emails about that have gone unanswered for approximately a year now...

**Comment by adur1990** [comment]
@erayd In the list above, I link correctly to the legacy repo, as passwordstore.org does. This repo, however, already links to the new browserpass-extension repo.

**Comment by erayd** [comment]
@adur1990 Gotcha - my mistake then; I thought you were saying that this repo should be updated to reflect the links in your post.
